apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: alb-controller
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  project: default

  source:
    repoURL: https://aws.github.io/eks-charts
    chart: aws-load-balancer-controller
    targetRevision: 1.7.1
    helm:
      parameters:
        - name: clusterName
          value: transcriber # REPLACE WITH YOUR CLUSTER NAME

        - name: region
          value: ap-south-1

        - name: vpcId
          value: vpc-0c2221a21898896ed # REPLACE WITH YOUR VPC ID 

        - name: serviceAccount.create
          value: "false"

        - name: serviceAccount.name
          value: aws-load-balancer-controller

        - name: serviceAccount.annotations.eks\.amazonaws\.com/role-arn
          value: arn:aws:acm:ap-south-1:894565488699:certificate/9c6bea05-cea5-4a95-a966-aeb5498521e1 # REPLACE WITH YOUR ALB CONTROLLER IRSA ROLE ARN

  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system

  syncPolicy:
    automated:
      prune: true
      selfHeal: true