apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"

spec:
  project: default

  source:
    repoURL: https://kubernetes-sigs.github.io/external-dns/
    chart: external-dns
    targetRevision: 1.14.5
    helm:
      parameters:
        - name: provider
          value: aws
          
        - name: domainFilters[0]
          value: arkadevops.in

        - name: policy
          value: upsert-only

        - name: registry
          value: txt

        - name: txtOwnerId
          value: transcriber

        - name: serviceAccount.create
          value: "false"

        - name: serviceAccount.name
          value: external-dns

        - name: serviceAccount.annotations.eks\.amazonaws\.com/role-arn
          value: arn:aws:iam::894565488699:role/transcriber-alb-role

  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system

  syncPolicy:
    automated:
      prune: true
      selfHeal: true