apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: transcriber-ingress
  namespace: {{ .Release.Namespace }}
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip

    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80},{"HTTPS":443}]'
    alb.ingress.kubernetes.io/ssl-redirect: "443"

    external-dns.alpha.kubernetes.io/hostname: {{ .Values.ingress.host }}

    {{- $secret := (lookup "v1" "Secret" .Release.Namespace "infra-secrets") }}
    {{- if $secret }}
    alb.ingress.kubernetes.io/certificate-arn: {{ $secret.data.CERT_ARN | b64dec | quote }}
    {{- end }}

spec:
  ingressClassName: alb
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: api
                port:
                  number: 8000

          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 80