apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "transcriber.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  annotations:
    {{- if .Values.irsaRoleArn }}
    eks.amazonaws.com/role-arn: {{ .Values.irsaRoleArn }}
    {{- end }}