apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.worker.replicaCount }}
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      serviceAccountName: {{ include "transcriber.serviceAccountName" . }}
      containers:
        - name: worker
          image: "{{ .Values.worker.image }}:{{ .Values.worker.tag }}"

          env:
            - name: DATABASE_URL
              value: "{{ .Values.env.DATABASE_URL }}"

            - name: S3_VIDEO_BUCKET_NAME
              value: "{{ .Values.env.S3_VIDEO_BUCKET_NAME }}"

            - name: REDIS_HOST
              value: "redis-master"

            - name: REDIS_PORT
              value: "6379"

          resources:
            {{- toYaml .Values.worker.resources | nindent 12 }}