apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: app-secrets
spec:
  refreshInterval: 1h

  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore

  target:
    name: app-secrets

  data:
    - secretKey: DATABASE_URL
      remoteRef:
        key: transcriber-secrets
        property: DATABASE_URL

    - secretKey: S3_VIDEO_BUCKET_NAME
      remoteRef:
        key: transcriber-secrets
        property: S3_VIDEO_BUCKET_NAME
    
    - secretKey: HUGGINGFACE_API_KEY
      remoteRef:
        key: transcriber-secrets
        property: HUGGINGFACE_API_KEY