apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: infra-secrets
spec:
  refreshInterval: 1h

  secretStoreRef:
    name: aws-ssm
    kind: ClusterSecretStore

  target:
    name: infra-secrets

  data:
    - secretKey: CLUSTER_NAME
      remoteRef:
        key: /transcriber/cluster_name

    - secretKey: VPC_ID
      remoteRef:
        key: /transcriber/vpc_id

    - secretKey: CERT_ARN
      remoteRef:
        key: /transcriber/certificate_arn

    - secretKey: IRSA_ROLE_ARN
      remoteRef:
        key: /transcriber/irsa_role_arn