apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "transcriber.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  annotations:
    eks.amazonaws.com/role-arn: 
      {{- $secret := (lookup "v1" "Secret" .Release.Namespace "infra-secrets") }}
      {{- if $secret }}
      eks.amazonaws.com/role-arn: {{ $secret.data.IRSA_ROLE_ARN | b64dec }}
      {{- end }}