apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.worker.replicaCount }}
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      serviceAccountName: {{ include "transcriber.serviceAccountName" . }}
      containers:
        - name: worker
          image: "{{ .Values.worker.image }}:{{ .Values.worker.tag }}"

          env:
            - name: REDIS_HOST
              value: "redis-master"

            - name: REDIS_PORT
              value: "6379"
            
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: DATABASE_URL

            - name: HUGGINGFACE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: HUGGINGFACE_API_KEY

            - name: STORAGE_MODE
              value: "s3"   # production

            - name: S3_VIDEO_BUCKET_NAME
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: S3_VIDEO_BUCKET_NAME

          resources:
            {{- toYaml .Values.worker.resources | nindent 12 }}