frontend:
  image: ghcr.io/kkarka/video-transcriber-frontend
  tag: frontend-504bf6e
  replicaCount: 2
  servicePort: 80
  port: 8080
api:
  image: ghcr.io/kkarka/video-transcriber-api
  tag: api-504bf6e
  replicaCount: 2
  servicePort: 5000
  resources:
    requests:
      cpu: "100m"
      memory: "128Mi"
    limits:
      cpu: "500m"
      memory: "512Mi"
worker:
  image: ghcr.io/kkarka/video-transcriber-worker
  tag: worker-504bf6e
  replicaCount: 1
  resources:
    requests:
      cpu: "200m"
      memory: "512Mi"
    limits:
      cpu: "1000m"
      memory: "1Gi"
ingress:
  host: transcriber.arkadevops.in
  certificateArn: ""
env:
  DATABASE_URL: ""
  S3_VIDEO_BUCKET_NAME: ""
serviceAccount:
  create: true
  name: app-sa
